name = "icraconsulting-com-v1"
compatibility_date = "2026-06-29"
main = "src/worker.ts"
workers_dev = false
preview_urls = false

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
run_worker_first = true

[[routes]]
pattern = "icraconsulting.com"
zone_name = "icraconsulting.com"

[[routes]]
pattern = "www.icraconsulting.com"
zone_name = "icraconsulting.com"
